Controllers/ValidationController.cs
using CCubed_2012.Classes;
using CCubed_2012.Interfaces;
using CCubed_2012.Models;
using CCubed_2012.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace CCubed_2012.Controllers
{
    public class ValidationController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IList<ILogger> _loggers;

        public ValidationController()
        {
            _loggers = new List<ILogger>();
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //return the view model with values selected from the database
        public ActionResult Index()
        {
            var viewModel = new ValidationFormViewModel()
            {
                Client =
                _context.CCubedControlTable
                    .Select(c => c.Client)
                    .Distinct().ToList(),
                Project =
                _context.CCubedControlTable
                    .Select(c => c.Project)
                    .Distinct().ToList(),
                CheckType =
                _context.CCubedControlTable
                    .Select(c => c.CheckType)
                    .Distinct().ToList()
            };
            return View(viewModel);
        }

        //When submit button is clicked, execute the below code in order to run validation
        [HttpPost]
        public ActionResult Result(ValidationFormViewModel viewModel)
        {
            //Add logging types for polymorphic logging to multiple destinations
            RegisterLogger(new DatabaseLogger());

            if (!ModelState.IsValid)
            {
                var formViewModel = new ValidationFormViewModel()
                {
                    ClientId = viewModel.ClientId,
                    ProjectId = viewModel.ProjectId,
                    CheckTypeId = viewModel.CheckTypeId
                };
                return View("Index", formViewModel);
            }

            var fileInfo =
              (from v in _context.CCubedControlTable
               where v.Client.Equals(viewModel.ClientId)
                     && v.Project.Equals(viewModel.ProjectId)
                     && v.CheckType.Equals(viewModel.CheckTypeId)
               select new {v.RawFilePath, v.TemplateFilePath, v.ColumnDelimiter }).FirstOrDefault();

            var resultViewModel = new ValidationResultViewModel() { Results = new List<ValidationResultModel>() };

            if (fileInfo != null)
            {
                var directoryInfo = new DirectoryInfo(fileInfo.TemplateFilePath);

                //Check to see if a template file exists. If not return No template file located to result view
                if (!directoryInfo.GetFiles("*.*").Any())
                {
                    var resultModel = new ValidationResultModel
                    {
                        IsValidated = "No Template File Located",
                        FileName = "Please Place A Template File Here: " + fileInfo.TemplateFilePath,
                        DiscrepancyColumns = ""
                    };

                    var executionLogRecord = InitializeLogModelObject(viewModel.ClientId, viewModel.ProjectId,
                        viewModel.CheckTypeId, "N/A", false, "No Template File Located", DateTime.Now);

                    foreach (var logger in _loggers)
                    {
                        logger.Log(executionLogRecord);
                    }

                    resultViewModel.Results.Add(resultModel);
                }
                else
                {

                    var templateFullFilePath = Directory.GetFiles(fileInfo.TemplateFilePath)[0];
                    var rawFullFilePaths = Directory.GetFiles(fileInfo.RawFilePath).ToList();
                    
                    //Check to see if template file is open
                    var templateFileInfo = new FileInfo(templateFullFilePath);

                    var fileManipulator = new FileManipulator();

                    if (fileManipulator.IsFileLocked(templateFileInfo))
                    {
                        var resultModel = new ValidationResultModel
                        {
                            IsValidated = "Template file is open in another program. Please close the file and try again.",
                            FileName = Path.GetFileName(templateFullFilePath),
                            DiscrepancyColumns = ""
                        };

                        var executionLogRecord = InitializeLogModelObject(viewModel.ClientId, viewModel.ProjectId,
                            viewModel.CheckTypeId, Path.GetFileName(templateFullFilePath), false, "Template File Open In Another Program", DateTime.Now);

                        foreach (var logger in _loggers)
                        {
                            logger.Log(executionLogRecord);
                        }

                        resultViewModel.Results.Add(resultModel);
                    }
                    else
                    {

                        foreach (var rawFullFilePath in rawFullFilePaths)
                        {
                            var resultModel = new ValidationResultModel();

                            //Check to see if raw file is open
                            var rawFileInfo = new FileInfo(rawFullFilePath);

                            if (fileManipulator.IsFileLocked(rawFileInfo))
                            {
                                resultModel.IsValidated =
                                    "Raw file is open in another program. Please close the file and try again.";
                                resultModel.FileName = Path.GetFileName(rawFullFilePath);
                                resultModel.DiscrepancyColumns = "";

                                var executionLogRecord = InitializeLogModelObject(viewModel.ClientId,
                                    viewModel.ProjectId,
                                    viewModel.CheckTypeId, Path.GetFileName(rawFullFilePath), false,
                                    "Raw File Open In Another Program", DateTime.Now);

                                foreach (var logger in _loggers)
                                {
                                    logger.Log(executionLogRecord);
                                }

                                resultViewModel.Results.Add(resultModel);
                            }
                            else
                            {

                                var columnChecker = new ColumnChecker(rawFullFilePath, templateFullFilePath);

                                var discrepancyString = columnChecker.ColumnDifference(1, fileInfo.ColumnDelimiter);

                                //if discrepancyString == "" then there were no discrepancies when validating column names/order
                                if (discrepancyString == "")
                                {
                                    resultModel.IsValidated = "Validated";
                                    resultModel.FileName = Path.GetFileName(rawFullFilePath);
                                    resultModel.DiscrepancyColumns = null;

                                    var executionLogRecord = InitializeLogModelObject(viewModel.ClientId,
                                        viewModel.ProjectId,
                                        viewModel.CheckTypeId, Path.GetFileName(rawFullFilePath), true, null,
                                        DateTime.Now);

                                    foreach (var logger in _loggers)
                                    {
                                        logger.Log(executionLogRecord);
                                    }
                                }

                                else
                                {
                                    resultModel.IsValidated = "Not Validated";
                                    resultModel.FileName = Path.GetFileName(rawFullFilePath);
                                    resultModel.DiscrepancyColumns = discrepancyString;

                                    var executionLogRecord = InitializeLogModelObject(viewModel.ClientId,
                                        viewModel.ProjectId,
                                        viewModel.CheckTypeId, Path.GetFileName(rawFullFilePath), false,
                                        discrepancyString,
                                        DateTime.Now);

                                    foreach (var logger in _loggers)
                                    {
                                        logger.Log(executionLogRecord);
                                    }

                                }

                                resultViewModel.Results.Add(resultModel);
                            }
                        }
                    }
                }
            }
            else
            {
                //return Content("Error with control table setup. Please contact a Developer");
                var resultModel = new ValidationResultModel
                {
                    IsValidated = "Incorrect Selection",
                    FileName = "Please Select Different Parameters",
                    DiscrepancyColumns = ""
                };

                var executionLogRecord = InitializeLogModelObject(viewModel.ClientId, viewModel.ProjectId,
                    viewModel.CheckTypeId, "N/A", false, "Invalid Parameter Selection", DateTime.Now);

                foreach (var logger in _loggers)
                {
                    logger.Log(executionLogRecord);
                }

                resultViewModel.Results.Add(resultModel);
            }

            return View(resultViewModel);

             
        }

Views/Validation/Index.cshtml
@model CCubed_2012.ViewModels.ValidationFormViewModel

@{
    ViewBag.Title = "Validation Form";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Check</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <style type="text/css">
        
        body {
            background: #e5f7e3 !important;
        }
        
    /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
         
    </style>

</head>

<body>

<h2>Validation Request</h2>

@using (Html.BeginForm("Result", "Validation"))
{
    <div class="form-group">
        @Html.LabelFor(m => m.Client)
        @Html.DropDownListFor(m => m.ClientId, new SelectList(Model.Client), "", new {@class = "form-control", id = "Client"})
        @Html.ValidationMessageFor(m => m.ClientId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Project)
        @Html.DropDownListFor(m => m.ProjectId, new SelectList(Model.Project), "", new {@class = "form-control", id = "Project"})
        @Html.ValidationMessageFor(m => m.ProjectId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.CheckType)
        @Html.DropDownListFor(m => m.CheckTypeId, new SelectList(Model.CheckType), "", new {@class = "form-control", id = "CheckType"})
        @Html.ValidationMessageFor(m => m.CheckTypeId)
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>

}

</body>
</html>

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")
}

<script type="text/javascript">
    //Disable Project if Client is not Selected
    $(document).ready(function () {

        if ($("#Client").val() === "")
        {
            $("#Project").attr('disabled', 'disabled');
        }
        else
        {
            $("#Project").removeAttr('disabled');
        }

        $("#Client").change(function () {

            if ($(this).val() === "")
            {
                $("#Project").attr('disabled', 'disabled');
            }
            else
            {
                $("#Project").removeAttr('disabled');
            }
        });
    });
    //Disable CheckType if Project is not selected
    $(document).ready(function () {

        if ($("#Project").val() === "") {
            $("#CheckType").attr('disabled', 'disabled');
        }
        else {
            $("#CheckType").removeAttr('disabled');
        }

        $("#Project").change(function () {

            if ($(this).val() === "") {
                $("#CheckType").attr('disabled', 'disabled');
            }
            else {
                $("#CheckType").removeAttr('disabled');
            }
        });
    });

    //Filter Dropdowns Base On Previous Dropdown Selections
    //Project Filter
    $('#Client').change(function (e) {
        e.preventDefault();
        var url = '@Url.Action("GetProjects")';
        var clientname = $('#Client option:selected').text();
        $.post(url, { clientName: clientname }, function (data) {
            var items = [];
            items.push("<option></option>");
            $.each(data, function () {
                items.push("<option value=" + this.Value + ">" + this.Text + "</option>");
            });
            $("#Project").html(items.join(' '));
        });
    });

    //CheckType Filter
    $('#Project').change(function (e) {
        e.preventDefault();
        var url = '@Url.Action("GetCheckTypes")';
        var clientname = $('#Client option:selected').text();
        var projectname = $('#Project option:selected').text();
        $.post(url, { clientName: clientname, projectName: projectname }, function (data) {
            var items = [];
            items.push("<option></option>");
            $.each(data, function () {
                items.push("<option value=" + this.Value + ">" + this.Text + "</option>");
            });
            $("#CheckType").html(items.join(' '));
        });
    });

</script>

Views/Validation/Result.cshtml
@{
    ViewBag.Title = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Results</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style type="text/css">
        #results td.green {
            color: green;
        }

        #results td.red {
            color: red;
        }

        body {
        background: #e5f7e3 !important;
        }
        /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
    </style>

</head>
<body>

<h2>Result</h2>

<div style="overflow-x:auto;">
    <table class="table table-bordered" id="results">
        <thead>
        <tr>
            <th>#</th>
            <th>Validation Status</th>
            <th>File Name</th>
            <th>Discrepancy Columns</th>
        </tr>
        </thead>
        <tbody>
        @{
            var count = 1;
            foreach (var result in Model.Results)
            {
                <tr>
                    <th scope="row">@count</th>

                    @if (result.IsValidated == "Validated")
                    {
                        <td class="green">@result.IsValidated</td>
                        <td class="green">@result.FileName</td>
                        <td class="green">@result.DiscrepancyColumns</td>
                    }
                    else
                    {
                        <td class="red">@result.IsValidated</td>
                        <td class="red">@result.FileName</td>
                        <td class="red">@result.DiscrepancyColumns</td>
                    }

                </tr>
                count++;
            }
        }
        </tbody>
    </table>
</div>

</body>
</html>

@section scripts
{
    <script>
        $(document)
            .ready(function() {
                $("#results").DataTable();
            });
    </script>
}